FPGA0=0
FPGA1=0
FPGA2=0
REG1=0
REG0=0
DAC1=0
REG2=0
DAC0=0
DAC2=0
DAC3=0
REG3=0
DAC4=0
DAC5=0
REG4=0
REG5=0
DAC6=0
pagedebug_page=0
gui_pos_console_x=10
gui_pos_console_y=10
gui_size_console_x=416
gui_size_console_y=439
gui_maximized_console=0
gui_position_x=100
gui_position_y=100
gui_pos_list_x=10
gui_pos_list_y=10
gui_size_list_x=400
gui_size_list_y=400
gui_maximized_list=0
debug_mode=0
gui_current_page_notebook=0
serial_port_num=0
